### ISSUE TITLE
✨ [Feature]: card list에 recoil에 저장된 데이터 내용 노출

### ISSUE THREAD

**Issue by dananote** [dananote/for-the-emotional-you#10]
## 🤔Description
card list에 recoil에 저장된 데이터 내용 노출

## 📍To-do
- [x] 감정 라벨, 날짜, 제목, 내용 노출
- [x] 최근 저장한 내용이 제일 상단에 오도록 노출
- [x] 마음 비우기 버튼을 누르면 리코일에서 해당 내용 삭제
- [x] 리코일에 저장된 데이터가 없다면 마음을 비워달라는 내용 노출

## 📃ETC
고려해야할것: 
1. 마음 비우기 버튼을 누르면 바로 삭제 되는 것이 아닌 모달창이 뜨는 기능 구현 
2. 감정라벨 필터 기능
