### ISSUE TITLE
✨ [Feature]: filter 기능 구현

### ISSUE THREAD

**Issue by dananote** [dananote/for-the-emotional-you#11]
## 🤔Description
드롭박스 UI 를 이용하여 사용자가 선택한 감정만 화면에 노출되도록 구현

## 📍To-do
- [x] 드롭박스를 클릭하면 네비가 열리고 하나를 선택하거나 그 외 화면을 클릭시 네비가 닫힘
- [x] 현재 선택한 필터에는 활성화가 되어 있고 선택하지 않은 것은 비활성화 되어 있음
- [x] 활성성화된대로 필터가 걸리면서 카드리스트에 보여지는 역역들이 필터링됨

## 📃ETC
기타사항
