### ISSUE TITLE
✨ [Feature]: Modal 기능 구현

### ISSUE THREAD

**Issue by dananote** [dananote/for-the-emotional-you#13]
## 🤔Description
사용자가 감정 비우기 버튼을 누르면 위로의 멘트가 나오는 기능 구현

## 📍To-do
- [x] 마음 비우기 버튼을 누르면 모달창 노출
- [x] 모달창 나오면 스크롤을 막음
- [x] 모달에서 버튼을 누르면 모달창이 닫힘
- [x] 모달창이 닫히면 리코일에서 클릭한 감정이 삭제됨
- [x] 멘트가 목데이터가 있는곳에 랜덤으로 노출됨

## 📃ETC
기타사항
