### ISSUE TITLE
✨ [Feature]: 반응형 구현

### ISSUE THREAD

**Issue by dananote** [dananote/for-the-emotional-you#14]
## 🤔Description
다양항 기기에 대응하기 위해 반응형 구현

## 📍To-do
- [ ] react-responsive 설치
- [ ] 모바일 버전시 감정메모와 작성페이지 구별
- [ ] 모바일 버전시 버튼을 통해 보여지는 페이지 노출 변경

## 📃ETC
...
