### ISSUE TITLE
💅 [Style]: Main page 마크업 및 스타일 구현

### ISSUE THREAD

**Issue by dananote** [dananote/for-the-emotional-you#2]
## 🤔Description
Main page 웹접근성을 고려한 마크업및 스타일링

## 📍To-do
- [x] 최대 넓이는 1100px 
- [x] 사용자가 직점 어떤 안좋은 일들이 있었는지 적는 란이 있고 이를 submit 할 버튼이 있다
- [x] 사용자가 지금까지 적은 감정들 리스트가 있으며 리스트가 없다면 감정을 버려달라는 문구가 있다
- [x] 사용자의 감정은 필터를 걸어서 확인할 수 있다.
- [x] 사용자의 감정 리스트는 해당 영역만 스크롤이 된다.

## 📃ETC
<구현할 화면>
<img width="900" alt="MacBook Pro 16_ - 4" src="https://github.com/dananote/for-the-emotional-you/assets/124513796/88ecbf4a-9ce9-467b-826e-7fa777440e25">
