### ISSUE TITLE
✨ [Feature]: 작성된 날짜 저장 및 모든 내용 입력안할시 에러

### ISSUE THREAD

**Issue by dananote** [dananote/for-the-emotional-you#9]
## 🤔Description
사용자가 실수없이 서비스를 이용하게 하기 위한 기능 추가

## 📍To-do
- [x] 날짜 또는 내용을 입력안할시 에러메시지 띄우기
- [x] 실수 허들을 줄이기 위해 감정 라벨은 기본적으로 하나 선택되어 있기
- [x] 본문내용 글자수 100자 제한 /  사용자가 직관적으로 확인하기 위한 실시간 글자수 카운트 및 초과시 입력 못하게 막기

## 📃ETC
기타사항
